# -*- coding: utf-8 -*-
"""task22.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kptJoazc0EC-6PNiIRAgOadnKkAN-_05
"""

import cv2 as cv
import numpy as np
import math
import matplotlib.pyplot as plt
from PIL import Image, ImageFilter


img = cv.imread("333.jpg", 0)
#####sobel######
sobelx = cv.Sobel(img,cv.CV_64F,1,0,ksize=5)
sobely = cv.Sobel(img,cv.CV_64F,0,1,ksize=5)
plt.subplot(2,2,3),plt.imshow(sobelx,cmap = 'gray')
plt.title('Sobel X'), plt.xticks([]), plt.yticks([])
plt.subplot(2,2,4),plt.imshow(sobely,cmap = 'gray')
plt.title('Sobel Y'), plt.xticks([]), plt.yticks([])
plt.show()

laplacian = cv.Laplacian(img,cv.CV_64F)
plt.subplot(2,2,2),plt.imshow(laplacian,cmap = 'gray')
plt.title('Laplacian'), plt.xticks([]), plt.yticks([])

from google.colab.patches import cv2_imshow,cv2
kernelx = np.array([[1,1,1],[0,0,0],[-1,-1,-1]])
kernely = np.array([[-1,0,1],[-1,0,1],[-1,0,1]])
img_prewittx = cv2.filter2D(img, -1, kernelx)
img_prewitty = cv2.filter2D(img, -1, kernely)

cv2_imshow( img_prewittx)
cv2_imshow(img_prewitty)

from google.colab.patches import cv2_imshow,cv2
kernelx = np.array([[-1,-1,-1],[-1,8,-1],[-1,-1,-1]])

img_log = cv2.filter2D(img, -1, kernelx)

cv2_imshow( img_log)